apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: benukapunchihewa/email-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: SERVICE_ACCESS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: email-config
                  key: service-access-token
            - name: AUTH_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: email-config
                  key: auth-service-base-url
            - name: ETHEREAL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: email-config
                  key: ethereal-username
            - name: ETHEREAL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: email-config
                  key: ethereal-password
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5001
